version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=my_database

  django:
    build:
      context: ./
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput&&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/app/static
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
