# Generated by Django 3.0.4 on 2020-03-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20200319_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
