# Generated by Django 3.0.4 on 2020-03-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_videofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoFile',
        ),
    ]
