# Generated by Django 3.0.4 on 2020-03-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20200326_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribed',
            field=models.ManyToManyField(blank=True, null=True, related_name='_profile_subscribed_+', to='video.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriber',
            field=models.ManyToManyField(blank=True, null=True, related_name='_profile_subscriber_+', to='video.Profile'),
        ),
    ]
